services:
  - type: web
    name: tidalbot-render
    env: docker
    repo: https://github.com/iamhajemi/tidalbot-render.git
    region: frankfurt
    plan: free
    branch: main
    buildCommand: git config --global --add safe.directory /app
    healthCheckPath: /health
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TIDAL_API_TOKEN
        sync: false
    scaling:
      minInstances: 1
      maxInstances: 1 