services:
  - type: worker
    name: tidalbot-render
    env: docker
    repo: https://github.com/yourusername/tidalbot-render.git
    region: frankfurt
    plan: free
    branch: main
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TIDAL_API_TOKEN
        sync: false
    scaling:
      minInstances: 1
      maxInstances: 1 